### ISSUE TITLE
Linux still crashes

### ISSUE THREAD

**Issue by Python1320** [gspetrou/Prone-Mod#5] opened 2016-11-11 12:01 UTC
```c++
HashInt(int) +0x2d             @ server_srv.so +0xdbebad
CStudioHdr::CActivityToSequenceMapping::SelectWeightedSequence(CStudioHdr*, int, int) +0xa0            @ server_srv.so +0x46b560
SelectWeightedSequence(CStudioHdr*, int, int) +0xa3            @ server_srv.so +0x46bd93
CBaseAnimating::SelectWeightedSequence(Activity) +0x2b                 @ server_srv.so +0x7946ab
CMultiPlayerAnimState::ComputeMainSequence() +0x148            @ server_srv.so +0x55c2e8
CMultiPlayerAnimState::ComputeSequences(CStudioHdr*) +0x38             @ server_srv.so +0x55c398
CHL2MPPlayerAnimState::Update(float, float) +0x9e              @ server_srv.so +0x51fb6e
CHL2MP_Player::PostThink() +0x92               @ server_srv.so +0xbaf9a2
CGMOD_Player::PostThink() +0x9f                @ server_srv.so +0x4dbdef
CPlayerMove::RunPostThink(CBasePlayer*) +0x37                  @ server_srv.so +0xcc5bb7
CPlayerMove::RunCommand(CBasePlayer*, CUserCmd*, IMoveHelper*) +0x8ae                  @ server_srv.so +0xcc76ce
CBasePlayer::PlayerRunCommand(CUserCmd*, IMoveHelper*) +0x9c           @ server_srv.so +0xca9f5c
CBasePlayer::PhysicsSimulate() +0x57b                  @ server_srv.so +0xcc0dbb
Physics_SimulateEntity(CBaseEntity*) +0x25b            @ server_srv.so +0xc89e0b
```

**Comment by gspetrou** [comment] 2016-11-11 14:46
Damnit, thanks I'll take a look this weekend

**Comment by gspetrou** [comment] 2016-11-12 20:06
Any idea what exactly was going on as the crash happened? Having difficulties trying to reproduce it.

**Comment by Kefta** [comment] 2016-11-21 12:35
Looks like a null CStudioHdr ptr. Don't know how that's manageable from the Lua state

**Comment by gspetrou** [comment] 2017-03-01 16:23
Haven't really heard anything about crashes in a couple months. If there is still an issue let me know but for now I'll close this issue.

**Closed as completed by gspetrou** 2017-03-01 16:23 UTC
